name = "Kpn_complex"
scheme = 18
url = "https://bigsdb.pasteur.fr/api/db/pubmlst_klebsiella_seqdef"
source = "Pasteur Insitute"

levels = [
  {name = "species", min = 0, max = 3.0207},
  {name = "subspecies", min = 3.0207, max = 6.9952},
  {name = "sublineage", min = 6.9952, max = 69.7933},
  {name = "clonalGroup", min = 69.7933, max = 93.1638},
  {name = "5", min = 93.1638, max = 98.4102},
  {name = "6", min = 98.4102, max = 798.8871},
  {name = "7", min = 98.8871, max = 99.3461},
  {name = "8", min = 99.3461, max = 99.6820},
  {name = "9", min = 99.6820, max = 99.8410},
  {name = "10", min = 99.8410, max = 100},
]
